services:
  octane:
    build:
      context: .
      dockerfile: .docker/octane/Dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    image: vrba/octane:local
    container_name: vrba-octane
    ports:
      - "${OCTANE_PORT:-8000}:8000"
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      OCTANE_SERVER: ${OCTANE_SERVER:-swoole}
      OCTANE_PORT: ${OCTANE_PORT:-8000}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS:-false}
      COMPOSER_CACHE_DIR: /tmp/composer
    volumes:
      - .:/var/www/html
      - composer-cache:/tmp/composer
    depends_on:
      - redis
      - supabase-db

  queue:
    build:
      context: .
      dockerfile: .docker/octane/Dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    image: vrba/octane:local
    container_name: vrba-queue
    command: ["php", "artisan", "horizon"]
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      COMPOSER_CACHE_DIR: /tmp/composer
    volumes:
      - .:/var/www/html
      - composer-cache:/tmp/composer
    depends_on:
      - redis

  scheduler:
    build:
      context: .
      dockerfile: .docker/octane/Dockerfile
      args:
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}
    image: vrba/octane:local
    container_name: vrba-scheduler
    command: ["php", "artisan", "schedule:work"]
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      COMPOSER_CACHE_DIR: /tmp/composer
    volumes:
      - .:/var/www/html
      - composer-cache:/tmp/composer
    depends_on:
      - redis

  vite:
    image: node:22-alpine
    container_name: vrba-vite
    working_dir: /var/www/html
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port $${VITE_PORT:-5173}"
    ports:
      - "${VITE_PORT:-5173}:5173"
    environment:
      VITE_PORT: ${VITE_PORT:-5173}
      NODE_ENV: development
    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules

  redis:
    image: redis:7-alpine
    container_name: vrba-redis
    command: redis-server --save "" --appendonly no
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data

  supabase-db:
    image: supabase/postgres:15.8.1.085
    container_name: vrba-supabase-db
    restart: unless-stopped
    ports:
      - "${SUPABASE_DB_PORT:-54322}:5432"
    environment:
      POSTGRES_PASSWORD: ${SUPABASE_DB_PASSWORD:-supabase}
      POSTGRES_DB: ${SUPABASE_DB_NAME:-postgres}
      POSTGRES_USER: ${SUPABASE_DB_USER:-postgres}
      PGPORT: 5432
    volumes:
      - supabase-data:/var/lib/postgresql/data

volumes:
  composer-cache:
  node_modules:
  redis-data:
  supabase-data:
